var user = {
  "login": "DeanGilewicz",
  "id": 8864519,
  "avatar_url": "https://avatars.githubusercontent.com/u/8864519?v=2",
  "gravatar_id": "",
  "url": "https://api.github.com/users/DeanGilewicz",
  "html_url": "https://github.com/DeanGilewicz",
  "followers_url": "https://api.github.com/users/DeanGilewicz/followers",
  "following_url": "https://api.github.com/users/DeanGilewicz/following{/other_user}",
  "gists_url": "https://api.github.com/users/DeanGilewicz/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/DeanGilewicz/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/DeanGilewicz/subscriptions",
  "organizations_url": "https://api.github.com/users/DeanGilewicz/orgs",
  "repos_url": "https://api.github.com/users/DeanGilewicz/repos",
  "events_url": "https://api.github.com/users/DeanGilewicz/events{/privacy}",
  "received_events_url": "https://api.github.com/users/DeanGilewicz/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Dean Gilewicz",
  "company": "",
  "blog": "",
  "location": "",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 7,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2014-09-22T17:46:00Z",
  "updated_at": "2014-10-08T19:40:43Z"
}
